services:
  app:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev
