services:
  app:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - /app/node_modules  # Evita que o host sobrescreva os node_modules do container
      - ./src/db/migrations:/app/src/db/migrations
    command: npm run start:dev
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    env_file:
    - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
