@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDczYzc3OC0zNzIwLTRhNWMtOGJhYS04YTgzNDk1N2M2YzEiLCJlbWFpbCI6ImFuZ2llQGVtYWlsLmNvbSIsImlhdCI6MTc0ODQ2MTgyMSwiZXhwIjoxNzQ4NDY1NDIxfQ.bmLH0RmJmmrWnx89baPVlDKOXzuzUZgJOslhzBiEj58

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Angelina Jolie",
  "email": "angie@email.com",
  "password": "P4$$word123"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "angie@email.com",
  "password": "P4$$word123"
}

### Query all users
GET http://localhost:3000/users
Authorization: Bearer {{token}}

### Query user by ID
GET http://localhost:3000/users/4c7897a1-3483-451e-9c0a-f68b61e802dd
Authorization: Bearer {{token}}

### Create post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My first post",
  "content": "This is the content of my first post",
  "authorId": "e2cc8f5c-2f5f-4b3f-883b-12b70487aaa7"
}

### Query all posts
GET http://localhost:3000/posts
Authorization: Bearer {{token}}

### Query post by ID
GET http://localhost:3000/posts/7f78e945-63d4-4b1c-b9da-0702ced2681c
Authorization: Bearer {{token}}

### Create comment
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "comment": "Great post!",
  "postId": "472d8da8-bbd4-45f3-b700-0636bcfbe307",
  "authorId": "4d73c778-3720-4a5c-8baa-8a834957c6c1"
}

### Query all comments
GET http://localhost:3000/comments
Authorization: Bearer {{token}}
