@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDczYzc3OC0zNzIwLTRhNWMtOGJhYS04YTgzNDk1N2M2YzEiLCJlbWFpbCI6ImFuZ2llQGVtYWlsLmNvbSIsImlhdCI6MTc0ODU1NjMxOCwiZXhwIjoxNzQ4NTU5OTE4fQ.nUGFDpJugN_jvn7519lDEw3RpuQTzVEz2wwsljlMVns

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Angelina Jolie",
  "email": "angie@email.com",
  "password": "P4$$word123"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "angie@email.com",
  "password": "P4$$word123"
}

### Query all users
GET http://localhost:3000/users
Authorization: Bearer {{token}}

### Query user by ID
GET http://localhost:3000/users/4c7897a1-3483-451e-9c0a-f68b61e802dd
Authorization: Bearer {{token}}

### Create post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My first post",
  "content": "This is the content of my first post",
  "authorId": "e2cc8f5c-2f5f-4b3f-883b-12b70487aaa7"
}

### Query all posts
GET http://localhost:3000/posts
Authorization: Bearer {{token}}

### Query post by ID
GET http://localhost:3000/posts/7f78e945-63d4-4b1c-b9da-0702ced2681c
Authorization: Bearer {{token}}

### Create comment
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "comment": "That's how they measure pants IN PRISON!",
  "postId": "05c40242-f9b1-454d-ba7a-4bde6d0ee76c",
  "authorId": "c270bc9a-9846-4041-b061-c652ae33d795"
}

### Query all comments
GET http://localhost:3000/comments
Authorization: Bearer {{token}}
